Repository mosaicml/composer, pull requests merged in 2022-02, with the labels that each got.

#281 Rename checkpoint API
  composer/trainer/checkpoint.py
  composer/trainer/checkpoint_hparams.py
  composer/trainer/trainer.py
  composer/yamls/models/glue/cola.yaml
  composer/yamls/models/glue/mnli-m.yaml
  composer/yamls/models/glue/mnli.yaml
  composer/yamls/models/glue/mrpc.yaml
  composer/yamls/models/glue/qnli.yaml
  composer/yamls/models/glue/qqp.yaml
  composer/yamls/models/glue/rte.yaml
  composer/yamls/models/glue/sst-2.yaml
  composer/yamls/models/glue/stsb.yaml
  tests/trainer/test_checkpoint.py
Labels: release

#262 Timm support
  composer/models/__init__.py
  composer/models/timm/__init__.py
  composer/models/timm/model.py
  composer/models/timm/timm_hparams.py
  composer/trainer/trainer_hparams.py
  composer/yamls/models/timm_resnet50_imagenet.yaml
  setup.py
  tests/test_hparams.py
  tests/test_load.py
  tests/test_model_registry.py
Labels: release

#120 Multiple Evaluator Datasets
  composer/core/evaluator.py
  composer/core/state.py
  composer/core/types.py
  composer/datasets/__init__.py
  composer/datasets/dataset_registry.py
  composer/datasets/evaluator.py
  composer/datasets/hparams.py
  composer/loggers/logger_hparams.py
  composer/loggers/tqdm_logger.py
  composer/profiler/dataloader_profiler.py
  composer/profiler/torch_profiler.py
  composer/trainer/trainer.py
  composer/trainer/trainer_hparams.py
  composer/utils/reproducibility.py
  examples/byo_trainer.py
  tests/algorithms/test_blurpool_algorithm.py
  tests/algorithms/test_channels_last.py
  tests/algorithms/test_layer_freezing.py
  tests/algorithms/test_stochastic_depth.py
  tests/datasets/test_synthetic_data.py
  tests/fixtures/dummy_fixtures.py
  tests/models/test_efficientnet.py
  tests/test_hparams.py
  tests/test_logger.py
  tests/test_state.py
  tests/trainer/test_checkpoint.py
  tests/trainer/test_ddp.py
  tests/trainer/test_ddp_sync_strategy.py
  tests/utils/classifer.py
Labels: release

#336 Add compression flag
  composer/trainer/checkpoint.py
  composer/trainer/trainer.py
  composer/utils/dist.py
  tests/trainer/test_checkpoint.py
Labels: release

#316 Copy `extra_init_params` to get rid of recursive config dicts
  composer/loggers/logger_hparams.py
Labels: release

#319 Composer Style Guide
  STYLE_GUIDE.md
Labels: release

#356 Add channels last standalone function
  composer/algorithms/channels_last/__init__.py
  composer/algorithms/channels_last/channels_last.py
  composer/algorithms/functional.py
  docs/source/algorithms.rst
  docs/source/method_cards/channels_last.md
  tests/algorithms/test_channels_last.py
Labels: enhancement, usability/API

#368 Support `import composer.functional as cf`
  composer/__init__.py
  composer/functional/__init__.py
Labels: usability/API

#379 Fix composer.functional page no longer showing functions
  docs/source/functional.rst
Labels: bug, documentation, release

#380 Functional API renaming part 1
  composer/algorithms/augmix/__init__.py
  composer/algorithms/augmix/augmix.py
  composer/algorithms/colout/__init__.py
  composer/algorithms/colout/colout.py
  composer/algorithms/cutmix/__init__.py
  composer/algorithms/cutmix/cutmix.py
  composer/algorithms/cutout/__init__.py
  composer/algorithms/cutout/cutout.py
  composer/algorithms/randaugment/__init__.py
  composer/algorithms/randaugment/randaugment.py
  composer/functional/__init__.py
  docs/source/algorithms.rst
  docs/source/functional.rst
  docs/source/method_cards/col_out.md
  docs/source/method_cards/cut_out.md
  docs/source/method_cards/cutmix.md
  docs/source/method_cards/rand_augment.md
  tests/algorithms/test_colout.py
  tests/algorithms/test_cutmix.py
Labels: usability/API

#320 Updated add_dataset_transform() to have flexible insertion point
  composer/algorithms/augmix/augmix.py
  composer/algorithms/colout/colout.py
  composer/algorithms/randaugment/randaugment.py
  composer/datasets/__init__.py
  composer/datasets/synthetic.py
  composer/utils/data.py
  docs/source/callbacks.rst
  examples/run_composer_trainer.py
  tests/datasets/test_add_dataset_transform.py
  tests/datasets/test_synthetic_data.py
Labels: release

#263 Rename `Event.TRAINING_START` to `Event.FIT`; remove `Event.TRAINING_END`
  composer/algorithms/README.md
  composer/algorithms/alibi/alibi.py
  composer/algorithms/augmix/augmix.py
  composer/algorithms/colout/colout.py
  composer/algorithms/randaugment/randaugment.py
  composer/algorithms/sam/sam.py
  composer/algorithms/scale_schedule/scale_schedule.py
  composer/algorithms/seq_length_warmup/seq_length_warmup.py
  composer/algorithms/swa/swa.py
  composer/callbacks/benchmarker.py
  composer/callbacks/run_directory_uploader.py
  composer/core/callback.py
  composer/core/engine.py
  composer/core/event.py
  composer/datasets/dataloader.py
  composer/datasets/synthetic.py
  composer/loggers/file_logger.py
  composer/loggers/mosaicml_logger.py
  composer/loggers/wandb_logger.py
  composer/profiler/dataloader_profiler.py
  composer/profiler/json_trace.py
  composer/trainer/trainer.py
  docs/source/core/algorithm.rst
  docs/source/core/engine.rst
  docs/source/core/event_table.rst
  docs/source/getting_started/welcome_tour.rst
  scripts/lint.sh
  tests/algorithms/test_channels_last.py
  tests/algorithms/test_colout.py
  tests/algorithms/test_progressive_resizing.py
  tests/algorithms/test_scale_schedule.py
  tests/callbacks/test_run_directory_uploader.py
  tests/datasets/test_synthetic_data.py
  tests/fixtures/dummy_fixtures.py
  tests/fixtures/models.py
  tests/profiler/test_json_profiler.py
  tests/test_engine.py
  tests/test_load.py
  tests/test_logger.py
  tests/test_mosaicml_logger.py
  tests/trainer/test_checkpoint.py
  tests/trainer/test_trainer.py
  tests/utils/classifer.py
Labels: release

#302 Documentation Outline
  docs/source/index.rst
  docs/source/notebooks/summary.rst
  docs/source/trainer/algorithms.rst
  docs/source/trainer/composer_model.rst
  docs/source/trainer/detailed_usage.rst
  docs/source/trainer/summary.rst
  docs/source/yahp/getting_started.rst
Labels: release

#449 Hide gen_interpolation_lambda in mixup like in cutmix and augmix
  composer/algorithms/mixup/__init__.py
  composer/algorithms/mixup/mixup.py
  composer/functional/__init__.py
  docs/source/method_cards/mix_up.md
  tests/algorithms/test_mixup.py
Labels: usability/API

#419 Trainer Docs + Param ordering + Alibi Export
  composer/algorithms/__init__.py
  composer/trainer/trainer.py
Labels: documentation

#370 Add NLP tutorial notebook
  examples/nlp_notebook_tutorial.ipynb
Labels: notebooks

#381 add kaggle notebook
  examples/medical_image_segmentation_composer.ipynb
Labels: notebooks

#422 Refactor Profiler init()
  composer/core/engine.py
  composer/core/state.py
  composer/optim/_time_conversion.py
  composer/profiler/__init__.py
  composer/profiler/dataloader_profiler.py
  composer/profiler/event_handler.py
  composer/profiler/json_trace.py
  composer/profiler/profiler.py
  composer/profiler/profiler_action.py
  composer/profiler/profiler_hparams.py
  composer/profiler/system_profiler.py
  composer/profiler/torch_profiler.py
  composer/trainer/trainer.py
  composer/trainer/trainer_hparams.py
  composer/utils/module_surgery.py
  docs/source/tables/update_alg_tables.py
  docs/source/tables/update_model_tables.py
  docs/source/tables/utils.py
  examples/profiler_demo.py
  examples/run_composer_profiler.py
  tests/profiler/test_json_profiler.py
  tests/profiler/test_profiler.py
Labels: release, usability/API

#476 Add missing defaults for one function
  composer/algorithms/cutout/cutout.py
Labels: usability/API

#330 Add custom methods notebook
  notebooks/custom_method_tutorial.ipynb
Labels: notebooks

#457 Matthew/docstrings update
  composer/algorithms/algorithm_registry.py
  composer/algorithms/alibi/__init__.py
  composer/algorithms/alibi/_gpt2_alibi.py
  composer/algorithms/alibi/alibi.py
  composer/algorithms/augmix/__init__.py
  composer/algorithms/augmix/augmix.py
  composer/algorithms/randaugment/__init__.py
  composer/algorithms/randaugment/randaugment.py
  composer/algorithms/seq_length_warmup/__init__.py
  composer/algorithms/seq_length_warmup/seq_length_warmup.py
  composer/algorithms/swa/__init__.py
  composer/algorithms/swa/swa.py
  composer/yamls/algorithms/alibi.yaml
  docs/source/doctest_fixtures.py
  docs/source/method_cards/alibi.md
  docs/source/method_cards/aug_mix.md
  docs/source/method_cards/rand_augment.md
  tests/algorithms/test_algorithm_registry.py
Labels: documentation

#470 docstring for callbacks
  composer/algorithms/alibi/__init__.py
  composer/algorithms/alibi/alibi.py
  composer/algorithms/augmix/__init__.py
  composer/algorithms/augmix/augmix.py
  composer/algorithms/randaugment/randaugment.py
  composer/algorithms/swa/__init__.py
  composer/algorithms/swa/swa.py
  composer/callbacks/__init__.py
  composer/callbacks/callback_hparams.py
  composer/callbacks/grad_monitor.py
  composer/callbacks/lr_monitor.py
  composer/callbacks/memory_monitor.py
  composer/callbacks/run_directory_uploader.py
  composer/callbacks/speed_monitor.py
  composer/core/callback.py
  composer/profiler/system_profiler.py
Labels: documentation

#483 Update docstrings for Colout, CutOut, CutMix, Layer Freezing, Mixup, Label Smoothing, Progressive Resizing
  composer/algorithms/colout/__init__.py
  composer/algorithms/colout/colout.py
  composer/algorithms/cutmix/__init__.py
  composer/algorithms/cutmix/cutmix.py
  composer/algorithms/cutout/__init__.py
  composer/algorithms/cutout/cutout.py
  composer/algorithms/label_smoothing/__init__.py
  composer/algorithms/label_smoothing/label_smoothing.py
  composer/algorithms/layer_freezing/__init__.py
  composer/algorithms/layer_freezing/layer_freezing.py
  composer/algorithms/mixup/__init__.py
  composer/algorithms/mixup/mixup.py
  composer/algorithms/progressive_resizing/__init__.py
  composer/algorithms/progressive_resizing/progressive_resizing.py
  composer/algorithms/randaugment/randaugment.py
  docs/source/doctest_fixtures.py
  tests/algorithms/test_cutmix.py
Labels: documentation

#522 Docstrings for composer.trainer
  composer/algorithms/factorize/factorize_core.py
  composer/algorithms/sam/sam.py
  composer/loggers/file_logger.py
  composer/optim/scheduler.py
  composer/trainer/__init__.py
  composer/trainer/_checkpoint.py
  composer/trainer/_deepspeed.py
  composer/trainer/_scale_schedule.py
  composer/trainer/_scaler.py
  composer/trainer/ddp.py
  composer/trainer/devices/__init__.py
  composer/trainer/devices/device.py
  composer/trainer/devices/device_cpu.py
  composer/trainer/devices/device_gpu.py
  composer/trainer/devices/device_hparams.py
  composer/trainer/trainer.py
  composer/trainer/trainer_hparams.py
  docs/source/doctest_fixtures.py
  docs/source/method_cards/scale_schedule.md
  tests/callbacks/test_memory_monitor.py
  tests/test_state.py
  tests/trainer/test_checkpoint.py
  tests/trainer/test_ddp_sync_strategy.py
  tests/trainer/test_scale_schedule.py
  tests/trainer/test_trainer.py
  tests/utils/trainer_fit.py
Labels: documentation

#473 Profiler docstrings
  .gitignore
  composer/core/engine.py
  composer/profiler/__init__.py
  composer/profiler/_event_handler.py
  composer/profiler/_profiler.py
  composer/profiler/_profiler_action.py
  composer/profiler/dataloader_profiler.py
  composer/profiler/json_trace.py
  composer/profiler/json_trace_merger.py
  composer/profiler/profiler_action.py
  composer/profiler/profiler_hparams.py
  composer/profiler/system_profiler.py
  composer/profiler/torch_profiler.py
  composer/trainer/trainer.py
  examples/profiler_demo.py
Labels: documentation

#516 Docstrings improvements for core.algorithm, core.callback, etc.
  composer/core/__init__.py
  composer/core/algorithm.py
  composer/core/callback.py
  composer/core/data_spec.py
  composer/core/engine.py
  composer/core/event.py
Labels: documentation

#326 Add functional/standalone API tutorial notebook
  notebooks/Composer_Functional.ipynb
Labels: notebooks

#603 Export Transforms in `composer.algorithms`
  composer/algorithms/__init__.py
Labels: usability/API
