Repository mosaicml/composer, pull requests merged in 2022-03, with the labels that each got.

#489 Add C4 Streaming dataset
  composer/datasets/__init__.py
  composer/datasets/c4.py
  composer/datasets/dataset_registry.py
  composer/trainer/trainer_hparams.py
  composer/yamls/models/gpt3_125m.yaml
  tests/test_dataset_registry.py
Labels: enhancement

#622 Matthew/functional docstrings update
  composer/algorithms/alibi/alibi.py
  composer/algorithms/augmix/augmix.py
  composer/algorithms/randaugment/randaugment.py
  composer/algorithms/seq_length_warmup/seq_length_warmup.py
  composer/algorithms/swa/swa.py
Labels: documentation

#598 docstrings improvements for core modules
  composer/__init__.py
  composer/core/__init__.py
  composer/core/evaluator.py
  composer/core/logging/logger.py
  composer/core/precision.py
  composer/core/serializable.py
  composer/core/state.py
  composer/core/time.py
  composer/core/types.py
Labels: documentation

#604 Update progressive resizing to work for semantic segmentation
  composer/algorithms/progressive_resizing/progressive_resizing.py
  tests/algorithms/test_progressive_resizing.py
Labels: research

#634 Add Uniform bounding box sampling option for CutOut and CutMix
  composer/algorithms/cutmix/cutmix.py
  composer/algorithms/cutout/cutout.py
  composer/algorithms/hparams.py
  tests/algorithms/test_cutmix.py
  tests/algorithms/test_cutout.py
Labels: research

#243 Vit
  .gitignore
  composer/models/__init__.py
  composer/models/vit_small_patch16/__init__.py
  composer/models/vit_small_patch16/hparams.py
  composer/models/vit_small_patch16/model.py
  composer/trainer/trainer_hparams.py
  composer/yamls/models/timm_vit_small_patch16.yaml
  composer/yamls/models/vit_small_patch16.yaml
  setup.py
  tests/test_hparams.py
  tests/test_load.py
Labels: research

#653 `composer.optim` docstrings
  composer/models/efficientnetb0/README.md
  composer/models/gpt2/README.md
  composer/models/resnet56_cifar10/README.md
  composer/models/ssd/hparams.yaml
  composer/optim/__init__.py
  composer/optim/decoupled_weight_decay.py
  composer/optim/optimizer_hparams.py
  composer/optim/scheduler.py
  composer/optim/scheduler_hparams.py
  composer/trainer/trainer_hparams.py
  composer/yamls/models/bert-base.yaml
  composer/yamls/models/deeplabv3_ade20k_unoptimized.yaml
  composer/yamls/models/efficientnetb0.yaml
  composer/yamls/models/glue/cola.yaml
  composer/yamls/models/glue/mnli-m.yaml
  composer/yamls/models/glue/mnli.yaml
  composer/yamls/models/glue/mrpc.yaml
  composer/yamls/models/glue/qnli.yaml
  composer/yamls/models/glue/qqp.yaml
  composer/yamls/models/glue/rte.yaml
  composer/yamls/models/glue/sst-2.yaml
  composer/yamls/models/glue/stsb.yaml
  composer/yamls/models/gpt2_1,3b.yaml
  composer/yamls/models/gpt2_125m.yaml
  composer/yamls/models/gpt2_13b.yaml
  composer/yamls/models/gpt2_2,7b.yaml
  composer/yamls/models/gpt2_350m.yaml
  composer/yamls/models/gpt2_52m.yaml
  composer/yamls/models/gpt2_6,7b.yaml
  composer/yamls/models/gpt2_760m.yaml
  composer/yamls/models/gpt2_83m.yaml
  composer/yamls/models/gpt3_125m.yaml
  composer/yamls/models/gpt3_350m.yaml
  composer/yamls/models/gpt3_760m.yaml
  composer/yamls/models/resnet101.yaml
  composer/yamls/models/resnet101_synthetic.yaml
  composer/yamls/models/resnet152.yaml
  composer/yamls/models/resnet152_synthetic.yaml
  composer/yamls/models/resnet18.yaml
  composer/yamls/models/resnet18_synthetic.yaml
  composer/yamls/models/resnet20_cifar10.yaml
  composer/yamls/models/resnet34.yaml
  composer/yamls/models/resnet34_synthetic.yaml
  composer/yamls/models/resnet50.yaml
  composer/yamls/models/resnet50_synthetic.yaml
  composer/yamls/models/resnet50_webdataset.yaml
  composer/yamls/models/resnet56_cifar10.yaml
  composer/yamls/models/resnet56_cifar10_synthetic.yaml
  composer/yamls/models/resnet9_cifar10.yaml
  composer/yamls/models/timm_resnet50_imagenet.yaml
  composer/yamls/models/timm_vit_small_patch16.yaml
  composer/yamls/models/vit_small_patch16.yaml
  docs/source/trainer/schedulers.rst
  notebooks/up_and_running_with_composer.ipynb
  tests/fixtures/dummy_fixtures.py
  tests/trainer/test_checkpoint.py
  tests/trainer/test_optimizer.py
  tests/trainer/test_scale_schedule.py
  tests/trainer/test_scheduler.py
Labels: documentation

#436 Migrating from PTL notebook
  notebooks/Migrating_from_PTL.ipynb
Labels: documentation, notebooks
